#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-google-api-services-storage
Version  : v1.rev115.1.23.0
Release  : 3
URL      : https://repo1.maven.org/maven2/com/google/apis/google-api-services-storage/v1-rev115-1.23.0/google-api-services-storage-v1-rev115-1.23.0.jar
Source0  : https://repo1.maven.org/maven2/com/google/apis/google-api-services-storage/v1-rev115-1.23.0/google-api-services-storage-v1-rev115-1.23.0.jar
Source1  : https://repo.gradle.org/gradle/libs-releases/com/google/apis/google-api-services-storage/v1-rev78-1.22.0/google-api-services-storage-v1-rev78-1.22.0.jar
Source2  : https://repo.gradle.org/gradle/libs-releases/com/google/apis/google-api-services-storage/v1-rev78-1.22.0/google-api-services-storage-v1-rev78-1.22.0.pom
Source3  : https://repo1.maven.org/maven2/com/google/apis/google-api-services-storage/v1-rev115-1.23.0/google-api-services-storage-v1-rev115-1.23.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-google-api-services-storage-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-google-api-services-storage package.
Group: Data

%description data
data components for the mvn-google-api-services-storage package.


%prep
%setup -q -n META-INF

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/google/apis/google-api-services-storage/v1-rev115-1.23.0
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/com/google/apis/google-api-services-storage/v1-rev115-1.23.0/google-api-services-storage-v1-rev115-1.23.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/google/apis/google-api-services-storage/v1-rev78-1.22.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/google/apis/google-api-services-storage/v1-rev78-1.22.0/google-api-services-storage-v1-rev78-1.22.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/google/apis/google-api-services-storage/v1-rev78-1.22.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/google/apis/google-api-services-storage/v1-rev78-1.22.0/google-api-services-storage-v1-rev78-1.22.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/google/apis/google-api-services-storage/v1-rev115-1.23.0
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/com/google/apis/google-api-services-storage/v1-rev115-1.23.0/google-api-services-storage-v1-rev115-1.23.0.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/google/apis/google-api-services-storage/v1-rev115-1.23.0/google-api-services-storage-v1-rev115-1.23.0.jar
/usr/share/java/.m2/repository/com/google/apis/google-api-services-storage/v1-rev115-1.23.0/google-api-services-storage-v1-rev115-1.23.0.pom
/usr/share/java/.m2/repository/com/google/apis/google-api-services-storage/v1-rev78-1.22.0/google-api-services-storage-v1-rev78-1.22.0.jar
/usr/share/java/.m2/repository/com/google/apis/google-api-services-storage/v1-rev78-1.22.0/google-api-services-storage-v1-rev78-1.22.0.pom
